SocialGouv/kosko-charts

- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env prod.ts.snap
- src/components/app/index.ts
- src/utils/createIngress.ts
- templates/simple/components/www.ts
Following #199 
This add a `withRedirections` option to handle more hostnames and 301 redirects
```js
withRedirections: {
destination: "www.website.fr",
hosts: ["website.fr", "old-website.com"],
}
```
> feat(withRedirections): add config.withRedirections

- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env prod.ts.snap
- src/components/hasura/index.ts
To prevent killing pods on high demand
> fix(hasura): increase RAM limits

- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env prod.ts.snap
- src/utils/createService.ts
Looks like we need a port name to accept a ServiceMonitor https://github.com/prometheus-operator/prometheus-operator/issues/416
> fix(service): add default service.port.name=http

- src/components/azure-pg/__snapshots__/index.test.ts.snap
- src/components/azure-pg/index.test.ts
- src/components/azure-pg/index.ts
when using `kosko-charts/azure-pg/create()` the `create-db` job used in development will now run in the `project-secret` namespace where `azure-admin-pg-user` secret resides.
this removes the necessity to get the secret from the repo (sealed-secret) or copy it to some namespace
> fix(azure-db): run create-db jobs in project secret namespace

- src/components/azure-pg/__snapshots__/index.test.ts.snap
- src/components/azure-pg/index.test.ts
- src/components/azure-pg/index.ts
> fix(azure-pg): dont try to load admin secret

- src/components/azure-pg/__snapshots__/create-db.test.ts.snap
- src/components/azure-pg/__snapshots__/index.test.ts.snap
- src/components/azure-pg/create-db.job.ts
This wont work directly : 
```
autodevops_495ad82f=> CREATE EXTENSION  uuid-ossp;
ERROR:  syntax error at or near "-"
LINE 1: CREATE EXTENSION  uuid-ossp;
^
autodevops_495ad82f=> CREATE EXTENSION "uuid-ossp";
CREATE EXTENSION
autodevops_495ad82f=>
```
> feat(azure-pg): add uuid-ossp extension on create

- e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- src/environments/gitlab/index.ts
This reverts commit 5e99bb056c50288bfac3ab2edeb17db21e7650cb.
restore review environments urls as [in autodevops](https://github.com/SocialGouv/gitlab-ci-yml/blob/master/base_autodevops.yml#L254)
> revert(gitlab): remove -dev2 suffix on application name

- docs/index.md
- src/utils/getHarborImagePath.test.ts
- src/utils/getHarborImagePath.ts
- src/utils/index.ts
add an utility to build the harbor registry image path during migration
> feat: add utils.getHarborImagePath

- src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap
- src/components/azure-pg/restore-db.job.test.ts
- src/components/azure-pg/restore-db.job.ts
use `CI_JOB_ID` instead of `CI_COMMIT_SHA` for the restore db job so we can run it multiple times if necessary
> fix(restore): enable multiple calls to job

- package.json
---
BREAKING CHANGE: You will now need to manually remove conflicting kosko related dependencies !
As we are now inline with the latest `kosko` version, we can restore the versioning responsibility on our side.
revert #477
> revert(pkg)!: restore kubernetes-models a direct dependency

- e2e/kitchen-sink/__tests__/__snapshots__/multihost.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- src/components/app/__snapshots__/index.test.ts.snap
- src/components/app/index.test.ts
- src/components/azure-pg/__snapshots__/index.test.ts.snap
- src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap
- src/components/azure-pg/create-db.job.ts
- src/components/azure-pg/index.test.ts
- src/components/azure-pg/index.ts
- src/components/azure-pg/restore-db.job.test.ts
- src/components/azure-pg/restore-db.job.ts
- src/environments/github/__snapshots__/index.test.ts.snap
- src/environments/github/index.ts
- src/environments/gitlab/__snapshots__/index.test.ts.snap
- src/environments/gitlab/index.ts
- src/environments/index.mock.ts
- src/types/index.ts
- src/utils/environmentSlug.test.ts
- src/utils/environmentSlug.ts
- templates/hasura/components/pg.ts
- templates/pgweb/components/pg.ts
- templates/sample/components/pg.ts
- tsconfig.build.json
---
BREAKING CHANGE: Our create database component is now creating one database per branch
Previously our `@socialgouv/kosko-charts/components/azure-pg` component was creating one database per commit. As it happen to be a rare need at @SocialGouv, we now switch to one database per branch.
BREAKING CHANGE: Unify commen `pg.ts` component use under the same function
Previously our `@socialgouv/kosko-charts/components/azure-pg` component was only handling the "dev"/"review" use case where we have to create the database and the user ourself. This ends up putting on the user land the responsibility of manually loading a sealedsecret in other case. As it happen to be a common need at @SocialGouv, we now deal with loading the file our creating the database as before if the named file does not …
> feat(azure-pg)!: use one database per branch

- e2e/kitchen-sink/__tests__/__snapshots__/multihost.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env preprod github.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env preprod github.ts.snap
- e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env preprod github.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env preprod github.ts.snap
- e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env preprod github.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap
- e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env preprod.ts.snap
- src/components/namespace/__snapshots__/index.test.ts.snap
- src/components/namespace/index.test.ts
- src/components/namespace/index.ts
- src/types/index.ts
- adds a `socialgouv/creator: autodevops` annotation on all namespaces
- `janitor/ttl: 15d` is added for dev envs only
- `createNamespace` can receive a `keepAlive` that disable this behaviour
with this, all dev namespaces will be destroyed after 15 days
> feat(components): add janitor annotations in dev

- e2e/templates/autodevops/app-ingress-anotations/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/app/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/azurepg/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/hasura/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/probes/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/probesPath/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/registry/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/resources/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/static-ingress-anotations/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/static/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/subdomain/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/yaml/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- templates/autodevops/kosko.toml
as a convention, `_` prefixed components should be excluded from production
> fix(autodevops): dont include namespaces in prod

- src/components/app/index.test.ts
- src/components/app/index.ts
When we have a `subDomainPrefix`, its appended to the generated `subdomain`, resulting in a possibly strings longer than 63 chars which seems to break external-dns
https://www.freesoft.org/CIE/RFC/1035/9.htm
> fix(app): fix very long hostnames

- e2e/kitchen-sink/__tests__/__snapshots__/multihost.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- src/components/namespace/__snapshots__/index.test.ts.snap
- src/components/namespace/index.test.ts
- src/components/namespace/index.ts
- reduce dev namespace ttl to 7 days instead of 15
- defaults to 1 day for `renovate*` branches
> feat(namespace): reduce ttl

- CHANGELOG.md
- README.md
- package.json
- src/components/app/index.test.ts
- src/components/app/index.ts
- src/environments/github/index.test.ts
- src/utils/environmentSlug.test.ts
- src/utils/environmentSlug.ts
- templates/autodevops/package.json
- templates/hasura/package.json
- templates/nginx/package.json
- templates/pgweb/package.json
- templates/redis/package.json
- templates/sample/package.json
- templates/testing/package.json
Trying to avoid too long `subdomain` problem.
Example:
- Working DNS/URL: https://api-code-du-travail-numerique-maxgfr-checkbox-53v22r.dev.fabrique.social.gouv.fr/
- Non working DNS/URL: https://api-code-du-travail-numerique-carolinebda-fix-remains-html-3yw7vf.dev.fabrique.social.gouv.fr/
Note that the Gitlab CI documentation says (https://docs.gitlab.com/14.4/ee/ci/variables/predefined_variables.html):
`CI_ENVIRONMENT_SLUG `: `The simplified version of the environment name, suitable for inclusion in DNS, URLs, Kubernetes labels, and so on. Available if environment:name is set. The slug is truncated to 24 characters.`
But a ticket linked to the doc talks about 63 chars: https://gitlab.com/gitlab-org/gitlab/-/issues/20941
> fix(slug): Reduce slug size from 63 to 53 chars

- src/components/netpol/__snapshots__/index.test.ts.snap
- src/components/netpol/index.ts
- change le nom de la netpol par défaut en `netpol-[namespace]`
- utilise `podSelector` au lieu de `namespaceSelector` + labels
> fix(netpol): use podSelector + fix default name

- src/components/netpol/__snapshots__/index.test.ts.snap
- src/components/netpol/index.test.ts
- src/components/netpol/index.ts
- src/components/pg/create-db-user.job.test.ts
Use namespace from environment if not provided
Allow usage of: 
```js
import { create } from "@socialgouv/kosko-charts/components/netpol";
export default create();
```
> fix(netpol): use default namespace

- src/components/oauth2-proxy/README.md
- src/components/oauth2-proxy/__snapshots__/index.test.ts.snap
- src/components/oauth2-proxy/index.test.ts
- src/components/oauth2-proxy/index.ts
Add basic [oauth2-proxy](http://oauth2-proxy.github.io/oauth2-proxy/) component
The component expect these 2 files to exist : 
- `environments/[env]/oauth2-proxy-configmap.yml`
- `environments/[env]/oauth2-proxy-sealed-secret.yml`
> feat: add oauth2-proxy component

- e2e/templates/autodevops/app-devInitContainerCommand/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- e2e/templates/autodevops/app-devInitContainerCommand/__tests__/__snapshots__/kosko generate --env preprod.ts.snap
- e2e/templates/autodevops/app-devInitContainerCommand/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/app-pgHostDev/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- e2e/templates/autodevops/app-pgHostDev/__tests__/__snapshots__/kosko generate --env preprod.ts.snap
- e2e/templates/autodevops/app-pgHostDev/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/azurepg/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap
- e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap
- src/components/azure-pg/__snapshots__/index.test.ts.snap
- src/components/azure-pg/index.ts
restore previous create-db behaviour: always use `azure-pg-admin-user` for db creation
en attendant de faire les fix de rm azure
> fix(azure-pg): fix create db secret

- e2e/templates/autodevops/pg/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- e2e/templates/autodevops/pg/__tests__/__snapshots__/kosko generate --env preprod.ts.snap
- e2e/templates/autodevops/pg/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- e2e/templates/autodevops/pg/__tests__/config.json
- e2e/templates/autodevops/pg/__tests__/kosko generate --env dev.ts
- e2e/templates/autodevops/pg/__tests__/kosko generate --env preprod.ts
- e2e/templates/autodevops/pg/__tests__/kosko generate --env prod.ts
- templates/autodevops/components/app.ts
- templates/autodevops/components/pg.ts
- templates/autodevops/utils/config.ts
In the autodevops template, `config.pg` will progressively replace the existing `azurepg` flag.
This one doesnt adds a create-db job. (it expects a previous `actions/create-db` run.)
Note: the apps attached secrets names still rely on `env.PG_USER_SECRET_PREFIX` which should now be set as `pg-user`
> feat(autodevops): add config.pg
