src/components/azure-db/__snapshots__/index.test.ts.snap, src/components/azure-db/create-db.job.ts, src/components/azure-db/index.test.ts, src/components/azure-db/index.ts, src/components/azure-db/params.ts, src/components/pg-secret/__snapshots__/index.test.ts.snap, src/components/pg-secret/create.ts, src/components/pg-secret/index.test.ts, src/components/pg-secret/index.ts, src/components/pg-secret/params.ts, src/utils/getPgServerHostname.ts
add azure-db/createDbJob and pg-secret/createPgSecret
=> feat: components/azure-db

tsconfig.json
=> build: make it node@12 friendly

package.json, src/components/azure-db/params.ts, src/utils/addToEnvFrom.ts, yarn.lock
=> feat(utils): add helperz

src/components/app/index.ts, src/utils/__snapshots__/createIngress.test.ts.snap, src/utils/createIngress.test.ts, src/utils/createIngress.ts
=> feat(ingress): allow mutliple hosts

src/components/azure-pg/__snapshots__/index.test.ts.snap, src/components/azure-pg/index.test.ts, src/components/pg-secret/create.ts
When creating a secret in the dev pipeline, add these variables to the generated secret
=> feat(pg-secret): add DB_URI and PGRST_DB_URI

e2e/.gitlab.env, e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env prod.ts.snap, src/components/nginx/index.ts, templates/simple/environments/.gitlab.env, templates/simple/package.json
- ~~rename default nginx component app name (app -> nginx)~~
- fix gitlab test values
- use linked kosko-charts for templates/simple
=> fix(template): add missing .gitlab.env file

e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/simple/kosko generate/__tests__/__snapshots__/--env prod.ts.snap, src/components/app/index.ts, src/components/hasura/index.ts, src/components/nginx/index.ts, src/components/pgweb/index.ts, src/utils/waitForPostgres.test.ts, src/utils/waitForPostgres.ts, templates/simple/components/hasura.ts, templates/simple/components/www.ts
`config.withPostgres` will add a reference to the `azure-pg-user` secret and a wait for PG initContainer
=> feat(withPostgres): add config.withPostgres

src/components/azure-pg/__snapshots__/index.test.ts.snap, src/components/azure-pg/index.test.ts, src/components/azure-pg/index.ts, src/environments/gitlab/__snapshots__/index.test.ts.snap, src/environments/gitlab/index.test.ts, src/environments/gitlab/index.ts, src/utils/assertEnv.test.ts, src/utils/assertEnv.ts
=> refactor(environments)!: remove io-ts from gitlab env

.gitignore, CONTRIBUTING.md, README.md
=> docs: update documentation 

jest.config.js
=> test: unit test should not wath the templates

src/components/azure-pg/index.test.ts, src/environments/gitlab/__snapshots__/index.test.ts.snap, src/environments/gitlab/index.test.ts, src/utils/__snapshots__/createIngress.test.ts.snap, src/utils/createIngress.test.ts
=> test: replace dev.fabrique by dev2.fabrique

src/components/azure-pg/__snapshots__/drop-autodevops-dbs.test.ts.snap, src/components/azure-pg/drop-autodevops-dbs.job.ts, src/components/azure-pg/drop-autodevops-dbs.test.ts
=> feat(azure-pg): add drop-autodevops-dbs job

src/utils/__snapshots__/waitForHttp.test.ts.snap, src/utils/addWaitForHttp.ts, src/utils/createDeployment.ts, src/utils/waitForHttp.test.ts, src/utils/waitForHttp.ts
This allows to add an initContainer that wait for a given url to be up
=> feat(utils): add wait for http

e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, e2e/testing/__fixtures__/environments/.gitlab-ci.env, e2e/testing/__fixtures__/environments/dev/.gitlab-ci.env, e2e/testing/__fixtures__/environments/preprod/.gitlab-ci.env, e2e/testing/__fixtures__/environments/prod/.gitlab-ci.env
=> e2e(testing): update general .gitlab.env

src/utils/__snapshots__/addInitContainerCommand.test.ts.snap, src/utils/addInitContainerCommand.test.ts, src/utils/addInitContainerCommand.ts, src/utils/getDeployment.ts
Can be used like this : 
```js
if (env.env === "dev") {
const deployment = getDeployment(manifests);
addInitContainerCommand(deployment, {
command: ["yarn"],
args: ["initdb"]
});
}
```
=> feat: add utils/addInitContainerCommand

e2e/kitchen-sink/__tests__/__snapshots__/multihost.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env prod.ts.snap, e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/nginx/kosko generate/__tests__/__snapshots__/--env prod.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/redis/kosko generate/__tests__/__snapshots__/--env prod.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env preprod.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env prod.ts.snap, e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, e2e/testing/__fixtures__/__tests__/__snapshots__/kosko generate --env prod.ts.snap, src/components/app/__snapshots__/index.test.ts.snap, src/components/app/index.ts
=> feat(app): add kapp annotations by default

src/components/azure-pg/__snapshots__/drop-db.test.ts.snap, src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-pg/drop-db.job.test.ts, src/components/azure-pg/drop-db.job.ts, src/components/azure-pg/restore-db.job.ts, src/components/azure-storage/__snapshots__/restore-container.job.test.ts.snap, src/components/azure-storage/restore-container.job.ts
Some jobs were not correctly cleaned
=> fix(jobs): add ttlSecondsAfterFinished

src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-pg/restore-db.job.test.ts, src/components/azure-pg/restore-db.job.ts, src/components/azure-storage/restore-container.job.test.ts, src/components/azure-storage/restore-container.job.ts, src/utils/addInitContainer.ts, src/utils/addWaitForPostgres.ts
- Add a `waitForPostgres` initContainer for the DB restore job
- Add a `postRestoreScript` to `createDbJob` that will trigger just after restore
=> feat(restore-db-job): add post-restore script

src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-pg/restore-db.job.ts
=> fix: fix wait user on restoreDb initContainer

src/utils/waitForHttp.ts
=> chore(renovate): make wait for http renovate friendly

package.json
--- 
BREAKING CHANGE: You will now need to manually install your kosko related dependencies !
As `kosko`, `@kosko/env`, etc... can have breaking version, we chose to put the versioning responsibility on the user side.
=> feat(pkg): make all kosko dependencies peerDependencies

e2e/kitchen-sink/__tests__/__snapshots__/multihost.ts.snap, e2e/kitchen-sink/components/www.ts, src/components/app/index.ts, src/components/autoscale/README.md, src/components/autoscale/__snapshots__/index.test.ts.snap, src/components/autoscale/index.test.ts, src/components/autoscale/index.ts, src/utils/getDeployment.ts
=> feat(autoscale): add autoscale component

README.md, templates/sample/package.json, templates/testing/__tests__/dev.ts, templates/testing/__tests__/preprod.ts, templates/testing/__tests__/prod.ts
Any reason we dont include test stuff directly in templates/sample ?
=> docs: some template fixes

src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-pg/restore-db.job.ts
Il faudrait pouvoir tester ca sur cdtn-admin
=> feat(pg-restore): exclude audit schema

src/utils/createDeployment.ts
=> feat(utils): allow volumes entry on deployment

src/components/azure-storage/__snapshots__/azureProjectVolume.test.ts.snap, src/components/azure-storage/azureProjectVolume.test.ts, src/components/azure-storage/azureProjectVolume.ts
=> feat(azure-storage): add project volume

src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-pg/restore-db.job.test.ts, src/components/azure-pg/restore-db.job.ts
---
⚠️ The pv/pvc require a fixed storage of 128Gi
⚠️ The pv/pvc will be on the same `*-secret` namespace
=> feat(azure-pg): make restore db uses azure files pv

src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-storage/__snapshots__/azureProjectVolume.test.ts.snap, src/components/azure-storage/azureProjectVolume.ts
=> fix(azure-storage): use env name instead of dynamic application name

src/components/azure-pg/__snapshots__/restore-db.job.test.ts.snap, src/components/azure-pg/restore-db.job.ts
=> fix(azure-pg): ensure to use constant pvc-pv naming

src/components/azure-storage/__snapshots__/fileshare.pvc.test.ts.snap, src/components/azure-storage/fileshare.pvc.test.ts, src/components/azure-storage/fileshare.pvc.ts
=> feat(azure-storage): add dynamic fileshare pvc

src/testing/fake/github-actions.env.ts
=> fix: Use SOCIALGOUV_BASE_DOMAIN in Github testing env

src/utils/environmentSlug.test.ts, src/utils/environmentSlug.ts
=> feat(utils): add gitlab like environmentSlug function

src/environments/github/__snapshots__/index.test.ts.snap, src/environments/github/index.test.ts, src/environments/github/index.ts
=> fix(environments): github branch env slug missing prefix

e2e/templates/autodevops/drop-db/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/templates/autodevops/drop-db/__tests__/config.json, e2e/templates/autodevops/drop-db/__tests__/kosko generate --env dev.ts, templates/autodevops/components/jobs/drop-db/index.ts, templates/autodevops/components/jobs/restore-db.ts
=> feat(autodevops): add drop db job

e2e/templates/autodevops/azurepg/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, src/components/azure-pg/__snapshots__/index.test.ts.snap, src/components/azure-pg/index.ts
=> fix(azure-pg): remove spec.template.metadata

e2e/templates/autodevops/azurepg/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, src/components/azure-pg/__snapshots__/index.test.ts.snap, src/components/azure-pg/create-db.job.test.ts, src/components/azure-pg/create-db.job.ts, src/components/azure-pg/index.ts
=> feat(azure-pg): tell kapp to skip update on create-db

e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env preprod github.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env prod github.ts.snap, src/utils/getHarborImagePath.test.ts, src/utils/getHarborImagePath.ts
fix the tag format when using github CI
=> fix(getHarborImagePath): allow from github too

e2e/templates/autodevops/app-devInitContainerCommand/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/templates/autodevops/app-devInitContainerCommand/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, e2e/templates/autodevops/app-devInitContainerCommand/__tests__/__snapshots__/kosko generate --env prod.ts.snap, e2e/templates/autodevops/app-pgHostDev/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/templates/autodevops/app-pgHostDev/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, e2e/templates/autodevops/app-pgHostDev/__tests__/__snapshots__/kosko generate --env prod.ts.snap, e2e/templates/autodevops/azurepg/__tests__/__snapshots__/kosko generate --env dev.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/hasura/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/pgweb/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev github.ts.snap, e2e/templates/sample/kosko generate/__tests__/__snapshots__/--env dev.ts.snap, src/components/azure-pg/__snapshots__/index.test.ts.snap, src/components/azure-pg/create-db.job.test.ts, src/components/azure-pg/create-db.job.ts
Add postgis extension because if have no other idea to enable it on an autodevops template :/
=> feat(azure-db): enable postgis by default

src/components/app/index.test.ts, src/components/app/index.ts
resolve some issues like https://github.com/SocialGouv/carnet-de-bord/runs/5180467575?check_suite_focus=true
=> fix(ingress): remove trailing hyphens
